config/routes.rb
Rails.application.routes.draw do
  resources :user_attachments
  devise_for :users
  resources :users
  get 'welcome/index'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :user_attachments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_attachment.rb
class UserAttachment < ActiveRecord::Base
	 mount_uploader :image, ImageUploader
   belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
  	user_path(resource)
	end
end

app/controllers/user_attachments_controller.rb
class UserAttachmentsController < ApplicationController
  # before_action :set_user_attachment, only: [:show, :edit, :update, :destroy]

  # GET /user_attachments
  # GET /user_attachments.json
  # def index
  #   @user_attachments = UserAttachment.all
  # end

  # GET /user_attachments/1
  # GET /user_attachments/1.json
  # def show
  # end

  # GET /user_attachments/new
  # def new
  #   @user_attachment = UserAttachment.new
  # end

  # GET /user_attachments/1/edit
  # def edit
  # end

  # POST /user_attachments
  # POST /user_attachments.json
  def create
    @user = User.find(params[:user_attachment][:user_id])
    params[:user_attachment][:image].each do |a|
      @user_attachment = @user.user_attachments.create!(:image => a)
    end
    redirect_to user_path(@user)
  end

  # PATCH/PUT /user_attachments/1
  # PATCH/PUT /user_attachments/1.json
  # def update
  #   respond_to do |format|
  #     if @user_attachment.update(user_attachment_params)
  #       format.html { redirect_to @user_attachment, notice: 'User attachment was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user_attachment }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user_attachment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /user_attachments/1
  # DELETE /user_attachments/1.json
  # def destroy
  #   @user_attachment.destroy
  #   respond_to do |format|
  #     format.html { redirect_to user_attachments_url, notice: 'User attachment was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_user_attachment
    #   @user_attachment = UserAttachment.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def user_attachment_params
    #   params.require(:user_attachment).permit(:user_id, :image)
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user_attachment = UserAttachment.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_attachments_helper.rb
module UserAttachmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_links.html.erb
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <span class="alert alert-success">Logged in as <strong><%= current_user.email %></strong></span>
    <%= link_to "Home", welcome_index_path, class: "btn btn-primary glyphicon glyphicon-home" %> |
    <%= link_to 'Edit profile', edit_user_registration_path, class: "btn btn-primary glyphicon glyphicon-pencil" %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
    <% else %>
    <%= link_to "Home", welcome_index_path, class: "btn btn-primary glyphicon glyphicon-home" %>
    <%= link_to "Log In", new_user_session_path, class: "btn btn-primary" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Umergram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render 'layouts/links' %>
  <%= yield %>
</body>
</html>

app/views/user_attachments/_form.html.erb
<%= form_for(@user_attachment) do |f| %>
  <% if @user_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_attachment.errors.count, "error") %> prohibited this user_attachment from being saved:</h2>

      <ul>
      <% @user_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_attachments/edit.html.erb
<h1>Editing User Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_attachment, class: "btn btn-primary" %> |
<%= link_to 'Back', user_attachments_path, class: "btn btn-primary" %>

app/views/user_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Attachments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_attachments.each do |user_attachment| %>
      <tr>
        <td><%= user_attachment.user_id %></td>
        <td><%= user_attachment.image %></td>
        <td><%= link_to 'Show', user_attachment, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_user_attachment_path(user_attachment), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', user_attachment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User attachment', new_user_attachment_path, class: "btn btn-primary" %>

app/views/user_attachments/new.html.erb
<h1>New User Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', user_attachments_path, class: "btn btn-primary" %>

app/views/user_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_attachment.user_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @user_attachment.image %>
</p>

<%= link_to 'Edit', edit_user_attachment_path(@user_attachment), class: "btn btn-primary" %> |
<%= link_to 'Back', user_attachments_path, class: "btn btn-primary" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions", class: "btn btn-primary">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading"><h4>Editing User</h4></div>
    <div class="panel-body">
			<%= render 'form' %>

			<%= link_to 'Show', @user, class: "btn btn-primary" %> |
			<%= link_to 'Back', users_path, class: "btn btn-primary" %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading"><h4>Listing Users</h4></div>
    <div class="panel-body">
      <p id="notice"><%= notice %></p>

      <table>
        <thead>
          <tr>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><strong><%= user.email %></strong></td>
              <td><%= link_to 'Show', user, class: "btn btn-primary" %></td>
              <td><%= link_to 'Edit', edit_user_registration_path(user), class: "btn btn-primary" %></td>
              <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New User', new_user_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading"><h4>New User</h4></div>
    <div class="panel-body">
			<%= render 'form' %>
			<%= link_to 'Back', users_path, class: "btn btn-primary" %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading"><h2>My Profile</h2></div>
    <div class="panel-body">
      <%= form_for(@user_attachment, :html => { :multipart => true }) do |f| %>
        <div class="field">
          <%= f.hidden_field :user_id, :value => @user.id %>
        </div>
        <div class="field">
          <%= f.file_field :image, :multiple => true, accept: "image/jpeg, image/jpg, image/gif, image/png" %>
        </div>
          <%= f.submit "Upload", class: "btn btn-primary" %></br></br>
      <% end %>

      <% @user.user_attachments.each do |b| %>
        <%= image_tag b.image_url, width: 100, height: 100 %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading"><h2>Welcome</h2>
    </div>
	</div>
</div>